class TourismPlace {
  final String name;
  final String location;
  final String imageAsset;
  final String imageNetwork;
  final String imageDetail1;
  final String imageDetail2;
  final String imageDetail3;
  final String description;
  final String openDays;
  final String openTime;
  final String ticketPrice;

  TourismPlace({
    required this.name,
    required this.location,
    required this.imageAsset,
    required this.imageNetwork,
    required this.imageDetail1,
    required this.imageDetail2,
    required this.imageDetail3,
    required this.description,
    required this.openDays,
    required this.openTime,
    required this.ticketPrice,
  });
}

var tourismPlaceList = [
  TourismPlace(
    name: 'Masjid Agung Baitul Mukminin Jombang',
    location: 'Jl. KH. A. Dahlan No.28, Jombatan, Kec. Jombang, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/masjid.jpg',
    imageNetwork: 'https://kabarjombang.com/wp-content/uploads/2021/04/masid-jami-1536x1228.jpg',
    imageDetail1: 'assets/images/masjid2.jpg',
    imageDetail2: 'assets/images/masjid3.jpg',
    imageDetail3: 'assets/images/masjid4.jpg',
    description: 'Masjid Agung Baitul Mukminin di Jombang merupakan salah satu landmark keagamaan yang megah dan menjadi pusat kegiatan umat Islam di kota tersebut. Dikenal dengan arsitektur yang indah dan megah, masjid ini memiliki kubah besar yang mencolok serta menara tinggi yang menjulang, menciptakan suasana yang menenangkan dan khusyuk bagi para jamaah. Masjid ini tidak hanya digunakan untuk ibadah sehari-hari, tetapi juga menjadi tempat berbagai kegiatan sosial dan keagamaan, termasuk pengajian, ceramah, dan acara-acara besar Islam lainnya. Terletak strategis di pusat kota, Masjid Agung Baitul Mukminin menjadi simbol spiritual dan budaya bagi masyarakat Jombang.',
    openDays: 'Setiap Hari',
    openTime: '24 Jam',
    ticketPrice: 'Gratis',
  ),
    TourismPlace(
    name: 'Makam Gus Dur (KH. Abdurrahman Wahid)',
    location: 'Jl. Irian Jaya Tebuireng No.10, Cukir, Kec. Diwek, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/makam.jpg',
    imageNetwork: 'https://storage.nu.or.id/storage/post/16_9/mid/pintu-masuk-makam-gus-dur-medium_1650688214.webp',
    imageDetail1: 'assets/images/makam2.jpg',
    imageDetail2: 'assets/images/makam3.jpg',
    imageDetail3: 'assets/images/makam4.jpg',
    description: 'Makam Gus Dur (KH. Abdurrahman Wahid) terletak di kompleks Pesantren Tebuireng, Jombang, Jawa Timur, dan menjadi salah satu tujuan ziarah utama di Indonesia. Dikenal sebagai tempat peristirahatan terakhir mantan Presiden RI ke-4 yang juga tokoh NU (Nahdlatul Ulama), makam ini sering dikunjungi oleh berbagai kalangan, dari masyarakat umum hingga tokoh-tokoh penting, untuk berziarah dan mengenang jasa-jasanya. Area makamnya sederhana namun khusyuk, dikelilingi oleh pepohonan rindang dan suasana yang tenang, mencerminkan kehidupan Gus Dur yang penuh dengan kebijaksanaan dan toleransi.',
    openDays: 'Setiap Hari',
    openTime: '08.00 - 15.00, 20.00 - 03.00',
    ticketPrice: 'Gratis',
  ),
    TourismPlace(
    name: 'Kampoeng Djawi',
    location: 'Dusun, Jl. Raya Gondang, Gondang, Carangwulung, Kec. Wonosalam, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/kampung.jpg',
    imageNetwork: 'https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:best,w_640/v1634025439/01gzqx4rcghhmymyqhcmtdqakc.jpg',
    imageDetail1: 'assets/images/kampung2.jpg',
    imageDetail2: 'assets/images/kampung3.jpg',
    imageDetail3: 'assets/images/kampung4.jpg',
    description: 'Kampoeng Djawi, terletak di Wonosalam, Jombang, adalah sebuah destinasi wisata yang menawarkan pengalaman budaya dan alam khas pedesaan Jawa. Dengan suasana yang asri dan udara yang sejuk, Kampoeng Djawi menyediakan berbagai kegiatan seperti outbond, camping, dan workshop seni tradisional, membuatnya ideal untuk liburan keluarga atau acara kelompok. Tempat ini juga dilengkapi dengan bangunan-bangunan tradisional Jawa, kolam renang alami, serta area persawahan yang luas, memberikan pengunjung kesempatan untuk merasakan kehidupan pedesaan yang autentik. Selain itu, keramahan warga lokal dan sajian kuliner tradisional menambah daya tarik Kampoeng Djawi sebagai tempat wisata yang menenangkan dan edukatif.',
    openDays: 'Setiap Hari',
    openTime: '08.00 - 16.00',
    ticketPrice: 'Rp50.000',
  ),
  TourismPlace(
    name: 'Tri Dharma Hong San Kiong',
    location: 'Jalan Raya Wangkal Gudo, Gudo, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/tridharma.jpg',
    imageNetwork: 'https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p2/133/2024/02/04/Klenteng-Hong-San-Kiong-1584969200.jpg',
    imageDetail1: 'assets/images/tridharma2.jpg',
    imageDetail2: 'assets/images/tridharma3.jpg',
    imageDetail3: 'assets/images/tridharma4.jpg',
    description: 'Tri Dharma Hong San Kiong adalah sebuah klenteng bersejarah yang terletak di Gudo, Jombang, Jawa Timur. Didirikan pada abad ke-18, klenteng ini merupakan pusat ibadah bagi umat Tridharma (Konfusianisme, Taoisme, dan Buddhisme) dan dikenal dengan arsitektur tradisionalnya yang indah serta atmosfer yang tenang dan sakral. Di dalamnya, terdapat berbagai patung dewa-dewi, altar, serta ornamen khas Tionghoa yang menambah keagungan dan nilai historis tempat ini. Selain menjadi tempat ibadah, Hong San Kiong juga berfungsi sebagai destinasi wisata budaya yang sering dikunjungi oleh wisatawan untuk menikmati keindahan seni dan budaya Tionghoa serta merasakan kedamaian spiritual yang ditawarkan.',
    openDays: 'Setiap Hari',
    openTime: '24 Jam',
    ticketPrice: 'Gratis',
  ),
  TourismPlace(
    name: 'Candi Rimbi',
    location: 'Area Sawah/Kebun, Ngrimbi, Kec. Bareng, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/candi.jpg',
    imageNetwork: 'https://4.bp.blogspot.com/-IJXX7XL7TXc/U1fXCOMqOzI/AAAAAAAABTE/cmaO40yAMWI/s1600/IMG_8325.JPG',
    imageDetail1: 'assets/images/candi2.jpg',
    imageDetail2: 'assets/images/candi3.jpg',
    imageDetail3: 'assets/images/candi4.jpg',
    description: 'Candi Rimbi adalah salah satu peninggalan sejarah di Jawa Tengah, Indonesia, yang terletak di desa Rimbi, kecamatan Kebumen. Candi ini memiliki arsitektur khas Jawa Tengah dengan ciri khas stupa yang menjulang tinggi. Meskipun ukurannya tidak sebesar candi-candi terkenal lainnya, Candi Rimbi tetap menarik minat wisatawan dengan keindahan relief-reliefnya yang halus dan berbagai ornamen arsitekturalnya. Selain sebagai tempat ibadah, candi ini juga menjadi tujuan wisata sejarah yang populer di kawasan tersebut.',
    openDays: 'Selasa Tutup',
    openTime: '08.00 - 16.00',
    ticketPrice: 'Rp5.000',
  ),
  TourismPlace(
    name: 'Alun-Alun Kabupaten Jombang',
    location: 'Jl. Diponegoro No.1-3, Kaliwungu, Kec. Jombang, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/alun.jpg',
    imageNetwork: 'https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/radarjombang/2021/12/alun-alun-jombang-dibuka-secara-resmi-untuk-umum-usai-nataru_m_311253.jpg',
    imageDetail1: 'assets/images/alun2.jpg',
    imageDetail2: 'assets/images/alun3.jpg',
    imageDetail3: 'assets/images/alun4.jpg',
    description: 'Alun-Alun Kabupaten Jombang adalah pusat kegiatan sosial dan budaya yang berlokasi di pusat kota Jombang, Jawa Timur, Indonesia. Terletak di antara dua bangunan penting, yakni Masjid Jami Al-Anwar dan Kantor Bupati Jombang, alun-alun ini menjadi tempat berkumpulnya masyarakat lokal dan pengunjung dari luar daerah. Dikelilingi oleh pepohonan rindang dan area terbuka yang luas, alun-alun ini menyediakan ruang untuk berbagai kegiatan mulai dari jalan-jalan santai hingga bermain tradisional. Sebagai pusat kegiatan kota, Alun-Alun Kabupaten Jombang juga sering menjadi lokasi untuk berbagai acara dan perayaan masyarakat setempat.',
    openDays: 'Setiap Hari',
    openTime: '24 Jam',
    ticketPrice: 'Gratis',
  ),
  TourismPlace(
    name: 'Waduk Jambe',
    location: 'Jambi, Bangsri, Kec. Plandaan, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/waduk.jpg',
    imageNetwork: 'https://faktajombang.com/wp-content/uploads/2021/11/mancing-di-waduk-jambe-bangsri-plandaan-jombang.jpg',
    imageDetail1: 'assets/images/waduk2.jpg',
    imageDetail2: 'assets/images/waduk3.jpg',
    imageDetail3: 'assets/images/waduk4.jpg',
    description: 'Waduk Jambe Plandaan merupakan salah satu destinasi wisata alam yang terletak di Kabupaten Jombang, Jawa Timur, Indonesia. Dikelilingi oleh hamparan sawah dan pepohonan hijau, waduk ini menawarkan suasana yang tenang dan nyaman bagi pengunjung yang ingin melepas penat. Selain menikmati pemandangan alam yang memikat, pengunjung juga dapat melakukan aktivitas rekreasi air seperti berperahu dan memancing. Waduk Jambe Plandaan sering menjadi tempat rekreasi favorit bagi warga lokal maupun wisatawan yang mengunjungi Jombang.',
    openDays: 'Setiap Hari',
    openTime: '24 Jam',
    ticketPrice: 'Gratis',
  ),
  TourismPlace(
    name: 'Kedung Cinet',
    location: 'Pojok, Tanggungan, Klitih, Kec. Plandaan, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/cinet.jpg',
    imageNetwork: 'https://img.kontenjatim.com/articles/archive_20230831/kedung-cinet-20230831-113753.jpg',
    imageDetail1: 'assets/images/cinet2.jpg',
    imageDetail2: 'assets/images/cinet3.jpg',
    imageDetail3: 'assets/images/cinet4.jpg',
    description: 'Kedung Cinet adalah sebuah ngarai di kawasan tengah hutan yang dikelilingi oleh tebing bebatuan kapur berukir yang berada di Desa Klitih, Kecamatan Plandaan, Kabupaten Jombang, Jawa Timur. Kedung Cinet menjadi salah satu Pariwisata di Jombang yang dikenal sebagai spot swafoto yang menarik.',
    openDays: 'Setiap Hari',
    openTime: '07.00 - 16.00',
    ticketPrice: 'Rp5.000',
  ),
  TourismPlace(
    name: 'Wisata Banyumili Wonosalam & P4S Etawa Salam',
    location: 'Carangwulung, Wonosalam, Gondang, Carangwulung, Kec. Wonosalam, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/banyu.jpg',
    imageNetwork: 'https://jombangkab.go.id/uploads/gambar/upload_e7e6c7a0b5cf2471cd7ac3a983d489eb.png',
    imageDetail1: 'assets/images/banyu2.jpg',
    imageDetail2: 'assets/images/banyu3.jpg',
    imageDetail3: 'assets/images/banyu4.jpg',
    description: 'Taman unik yang dipenuhi miniatur rumah beratap rumput & latar unik lainnya untuk tempat berfoto.',
    openDays: 'Setiap Hari',
    openTime: '08.00 - 16.00',
    ticketPrice: 'Rp5.000',
  ),
  TourismPlace(
    name: 'Wana Wisata Bukit Pinus Wonosalam',
    location: 'Jl. Boklorobubuh, Area Sawah/Kebun, Perhutani, Carangwulung, Kec. Wonosalam, Kabupaten Jombang, Jawa Timur',
    imageAsset: 'assets/images/pinus.jpg',
    imageNetwork: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1f/14/47/3a/wana-wisata-bukit-pinus.jpg?w=1100&h=-1&s=1',
    imageDetail1: 'assets/images/pinus2.jpg',
    imageDetail2: 'assets/images/pinus3.jpg',
    imageDetail3: 'assets/images/pinus4.jpg',
    description: 'Sebuah wahana rekreasi yang berada ditengah hutan pinus dikawasan carangwulung yang telah dikelola dan ditata dengan baik dan rapi, yang mana akan membuat wisatawan nyaman mengunjunginya, berhawa sejuk khas pegunungan dan dekat dengan kawasan wisata lain, ini merupakan nilai tambah yang akan mempermudah wisatawan untuk aneka kunjungan dalam satu lingkungan wana wisata.',
    openDays: 'Setiap Hari',
    openTime: '08.00 - 16.00',
    ticketPrice: 'Rp7.500',
  ),
];